VERSION 0.7

main:
  FROM node:20.4-slim

src:
  FROM +main
  
  WORKDIR /frontend
  COPY . .

  RUN npm ci

build:
  FROM +src
  RUN npm run build
  ENTRYPOINT ["npm", "run"]
  SAVE IMAGE frontend

lint:
  FROM +src
  RUN npm run type-check
  RUN npm run lint
