VERSION 0.7

main:
  FROM node:20.4-slim

src:
  FROM +main
  
  WORKDIR /frontend
  COPY . .

  RUN npm ci

prebuild:
  FROM +src
  RUN npm run build
  SAVE ARTIFACT ./dist # AS LOCAL ./dist

build:
  FROM caddy:2.6-alpine

  COPY ./Caddyfile /etc/caddy/Caddyfile
  COPY +prebuild/dist /dist

  EXPOSE 8080
  SAVE IMAGE sprutton1/frontend:latest

lint:
  FROM +src
  RUN npm run type-check
  RUN npm run lint
