version: 3
  
tasks:

  help:
  desc: Display this help screen
  silent: true
  cmds:
    - task --list

### Composite Tasks ###

  build:
   desc: Build all container images
   silent: true
   deps:
     - build_backend
     - build_frontend

  lint:
   desc: Run all of the linters
   silent: true
   deps:
     - lint_backend
     - lint_frontend

### Tasks ###       

  build_backend:
    silent: true
    cmds:
      - |
        DIR=$(git rev-parse --show-toplevel)
        pushd $DIR/backend
        earthly +build
        popd

  build_frontend:
    silent: true
    cmds:
      - |
        DIR=$(git rev-parse --show-toplevel)
        pushd $DIR/frontend
        earthly +build
        popd 

  lint_backend:
    silent: true
    cmds:
      - |
        DIR=$(git rev-parse --show-toplevel)
        pushd $DIR/backend
        earthly +lint
        popd

  lint_frontend:
    silent: true
    cmds:
      - |
        DIR=$(git rev-parse --show-toplevel)
        pushd $DIR/frontend
        earthly +lint
        popd 

  test:
    desc: Run tests (in backend)
    silent: true
    cmds:
      - |
        DIR=$(git rev-parse --show-toplevel)
        pushd $DIR/backend
        earthly +test
        popd

