apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskly.fullname" . }}-fe
  labels:
    {{- include "taskly.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "taskly.selectorLabels" . | nindent 4 }}
    app: frontend
