name: CI Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '!**/README.md'
  pull_request:
    paths:
      - 'backend/**'
      - '!**/README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the Backend
    steps:
      - uses: arduino/setup-task@v1
      - uses: earthly/actions-setup@v1
      - uses: actions/checkout@v2

      - name: test
        run: task test

  build:
    runs-on: ubuntu-latest
    name: Build the Backend
    steps:
      - name: build
        run: task build_backend

  push:
    runs-on: ubuntu-latest
    name: Push the Backend image
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push
        run: docker push sprutton1/backend
